---
abstract: 'A verbose version of system()'
author:
  - 'Drew Stephens <drew@dinomite.net>'
build_requires:
  Capture::Tiny: 0.06
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Shell-Verbose
provides:
  Shell::Verbose:
    file: lib/Shell/Verbose.pm
    version: 0.1
requires:
  perl: v5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
