---
abstract: 'A verbose version of system()'
author:
  - 'Drew Stephens <drew@dinomite.net>'
build_requires:
  Capture::Tiny: 0.06
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Shell-Verbose
version: 0.1.1
